<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-22 19:23

import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 4.2.2 on 2025-07-28 20:46

>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('base', '0002_initial'),
=======
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Appointment Schedualed', 'Appointment Schedualed'), ('Appointment Cancelled', 'Appointment Cancelled')], max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
<<<<<<< HEAD
                ('dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Appointment Scheduled', 'Appointment Scheduled'), ('Appointment Cancelled', 'Appointment Cancelled')], max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment_notification', to='base.appointment')),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
=======
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
    ]
