<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2.2 on 2025-07-28 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('base', '0003_initial'),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
<<<<<<< HEAD
=======
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment_notification', to='base.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient'),
        ),
    ]
