<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-22 19:23

import django.db.models.deletion
from django.db import migrations, models
=======
# Generated by Django 4.2.2 on 2025-07-28 20:46

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to='doctor.doctor'),
=======
            model_name='service',
            name='available_doctor',
            field=models.ManyToManyField(blank=True, to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointment'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.appointment'),
        ),
        migrations.AddField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='base.appointment'),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
        ),
    ]
