# Generated by Django 4.2.2 on 2025-07-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='service',
            name='available_doctor',
        ),
    ]
