# Generated by Django 4.2.2 on 2025-08-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meetlink',
            field=models.URLField(blank=True, help_text='Google Meet URL (e.g. https://meet.google.com/abc-defg-hij)', max_length=500, null=True),
        ),
    ]
