# Generated by Django 4.2.2 on 2025-07-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appointment_doctor_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='service',
            name='available_doctor',
        ),
    ]
