# Generated by Django 4.2.2 on 2025-07-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_initial'),
        ('patient', '0004_initial'),
        ('base', '0006_remove_appointment_doctor_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_doctor',
            field=models.ManyToManyField(blank=True, to='doctor.doctor'),
        ),
    ]
