<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-22 19:23

import django.utils.timezone
from django.db import migrations, models
=======
# Generated by Django 4.2.2 on 2025-07-28 20:46

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('base', '0001_initial'),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
=======
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=100, null=True)),
<<<<<<< HEAD
                ('next_available_appointment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
=======
                ('next_available_appointment', models.CharField(blank=True, max_length=100, null=True)),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New Appointment', 'New Appointment'), ('Appointment Cancelled', 'Appointment Cancelled')], max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointment_notification', to='base.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
>>>>>>> e387db8dff2078def121911fddcba075f9b6b62d
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
    ]
