# Generated by Django 4.2.2 on 2025-07-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_appointment_doctor_remove_appointment_patient_and_more'),
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
