# Generated by Django 4.2.2 on 2025-08-04 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_available_appointment',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
